name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Backend - Install & Lint
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pyflakes || true

      - name: Transactions - Install & Lint
        working-directory: transactions
        run: |
          if [ -f package.json ]; then npm ci || npm i; fi
          npx eslint . || true

      - name: Frontend - Build
        working-directory: studentportfolio
        run: |
          if [ -f package.json ]; then npm ci && npm run build; else echo "Static site - no build"; fi

      - name: Compose config check
        run: docker compose -f docker-compose.yml config

      - name: Archive compose artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compose-and-config
          path: |
            docker-compose.yml
            nginx.conf